name: Draft Review Checklist

on:
  pull_request:
    types: [opened, edited]
    branches:
      - 'release_[0-9].[0-9]_draft'

jobs:
  review-checklist:
    name: Draft Review Checklist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Review Checklist
            Does this PR follow the [development guidelines](https://algebraicjulia.github.io/Catlab.jl/dev/devdocs/style/)? Following is a *partial* checklist:
            **Tests**
            - [ ] New features and bug fixes have unit tests
            - [ ] New modules have tests that are ultimately called by the test runner (\`test/runtests.jl\`)
            - [ ] Existing tests have not been deleted
            - [ ] Code coverage &gt;= 90% or reduction justified in PR`,
            })
