name: 'PR Tasks Completed Check'
on:
  pull_request:
    types: [opened, edited]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: macqueenism/required-task-checker-action@v0.2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
